version: "3"
services:
  spark-master:
    image: spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8888:8888"
    volumes:
      - "./data:/home/data"
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8080"
    command: "/start-master.sh"

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - "./data:/home/data"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_LOCAL_IP=spark-worker-1"
    command: "/start-worker.sh"

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - "./data:/home/data"
    networks:
      - spark-network
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_LOCAL_IP=spark-worker-2"
    command: "/start-worker.sh"

networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default